### PR TITLE
extra utilities 2

### PR DESCRIPTION
**Pull request by bogger33**
This adds:

Stoneburnt
Redstone Crystal
Lunar Reactive Dust
Moonstone
Magical Wood
Demon Metal

### CODE REVIEW

**Comment by GenDeathrow** [comment]
I not accepting this because we are getting things ported over to 1.11 after I finish that I get this in both versions.

**Comment by bogger33** [comment]
Sounds great! I'm gonna do actually additions next, probably.

**Comment by bogger33** [comment]
what's left to do on the 1.11 port? Would it be something that someone else could help with?

**Comment by bogger33** [comment]
so... port's done

**Comment by GenDeathrow** [comment]
Port is done, Im currently working on Chickens mod as well now, I am getting some fixes done, and have a few other mods to work on.... but I will do some testing soon.

**Comment by GenDeathrow** [comment]
I'll try to get all your updates to more chickens done this weekend.. @bogger33 also, since you have done so much, what is your curse forge so I can add you as a contributor to More chickens..

**Comment by bogger33** [comment]
so this got merged but never put up on curse, was that by accident or did it just not happen yet?

**Comment by GenDeathrow** [comment]
.. oops, tbh RL things had come up recently I had just completely forgotten about it.  I believe it all worked.

**Comment by bogger33** [comment]
yeah it should, sorry about that mess from my aluminum pull request by the way. I did test all of them as good as I could.

**Comment by GenDeathrow** [comment]
dont worry about it.. I have made tons of mistakes. and that was one I didn't even know could happen. but its a good thing we found it

**Comment by bogger33** [comment]
@GenDeathrow so uh, any chance of looking at it this weekend maybe?

**Comment by GenDeathrow** [comment]
hoping so, I ended up going out of town last weekend.

**Pull request merged**
