### PR TITLE
add common gem chickens

### PR DESCRIPTION
**Pull request by bogger33**
This adds the following chickens:

Amethyst
Amber
Garnet
Tanzanite
Topaz
Ruby
Sapphire
Malachite
Peridot

It also adds the german language files in addition to the english, hopefully with no typos this time.

### CODE REVIEW

**Comment by GenDeathrow** [comment]
Do you have mincraft curse forge account?

**Comment by bogger33** [comment]
I don't, I'm on linux so the curse/twitch client doesn't really work for me

**Comment by bogger33** [comment]
Oh I actually just found a mistake as well, Amethyst chickens drop gemRuby instead of gemAmethyst.

**Comment by GenDeathrow** [comment]
if you would push a pr so I don't forget about it. Im heading into work now, So its a good chance for me to forget from now to then.

**Comment by bogger33** [comment]
no problem!

**Pull request merged**
